//Copyright(c) 2025 gdemers
//
//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files(the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and /or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions :
//
//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//SOFTWARE.
#include "PrivateTags.h"

// @gdemers InventorySample.Item.Type
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_TYPE_OFFENSIVE, TEXT("InventorySample.Item.Type.Offensive"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_TYPE_DEFENSIVE, TEXT("InventorySample.Item.Type.Defensive"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_TYPE_SUPPORT, TEXT("InventorySample.Item.Type.Support"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_TYPE_CRAFTING, TEXT("InventorySample.Item.Type.Crafting"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_TYPE_STORAGE, TEXT("InventorySample.Item.Type.Storage"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_TYPE_ATTACHMENT, TEXT("InventorySample.Item.Type.Attachment"));
// @gdemers InventorySample.Item.State
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_PENDING_SPAWN, TEXT("InventorySample.Item.State.Pending.Spawn"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_PENDING_SWAP, TEXT("InventorySample.Item.State.Pending.Swap"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_PENDING_TRADE, TEXT("InventorySample.Item.State.Pending.Trade"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_PENDING_SELL, TEXT("InventorySample.Item.State.Pending.Sell"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_PENDING_BUY, TEXT("InventorySample.Item.State.Pending.Buy"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_PENDING_DISCARD, TEXT("InventorySample.Item.State.Pending.Discard"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_PENDING_CONSUMPTION, TEXT("InventorySample.Item.State.Pending.Consumption"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_SWAPPED, TEXT("InventorySample.Item.State.Swapped"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_TRADED, TEXT("InventorySample.Item.State.Traded"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_SOLD, TEXT("InventorySample.Item.State.Sold"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_BOUGHT, TEXT("InventorySample.Item.State.Bought"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_DISCARD, TEXT("InventorySample.Item.State.Discard"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_CONSUMED, TEXT("InventorySample.Item.State.Consumed"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_ACTIVE, TEXT("InventorySample.Item.State.Active"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_INSTANCED, TEXT("InventorySample.Item.State.Instanced"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_EQUIPPED, TEXT("InventorySample.Item.State.Equipped"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_STATE_HOLSTERED, TEXT("InventorySample.Item.State.Holstered"));
// @gdemers InventorySample.Item.Visibility
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_VISIBILITY_ONLY_WHEN_ACTIVE, TEXT("InventorySample.Item.Visibility.AlwaysVisible"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_VISIBILITY_ALWAYS_VISIBLE, TEXT("InventorySample.Item.Visibility.OnlyWhenActive"));
// @gdemers InventorySample.Item.Behaviour
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_BEHAVIOUR_CAN_SPAWN_ACTOR, TEXT("InventorySample.Item.Behaviour.CanSpawnActor"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_BEHAVIOUR_CAN_STACK, TEXT("InventorySample.Item.Behaviour.CanStack"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_BEHAVIOUR_CAN_BE_CONSUMED, TEXT("InventorySample.Item.Behaviour.CanBeConsumed"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_BEHAVIOUR_CAN_BE_DROPPED, TEXT("InventorySample.Item.Behaviour.CanBeDropped"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_BEHAVIOUR_DESTROY_ON_DROP, TEXT("InventorySample.Item.Behaviour.DestroyOnDrop"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_BEHAVIOUR_PERSIST_ON_DROP, TEXT("InventorySample.Item.Behaviour.PersistOnDrop"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_BEHAVIOUR_DESTROY_WHEN_EMPTY, TEXT("InventorySample.Item.Behaviour.DestroyWhenEmpty"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_BEHAVIOUR_PICKUP_INTO_ACTIVE_SLOT, TEXT("InventorySample.Item.Behaviour.Pickup.IntoActiveSlot"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_BEHAVIOUR_PICKUP_INTO_STORAGE, TEXT("InventorySample.Item.Behaviour.Pickup.IntoStorage"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_BEHAVIOUR_TRANSIENT_PREVENT_DROPPING, TEXT("InventorySample.Item.Behaviour.Transient.PreventDropping"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_BEHAVIOUR_TRANSIENT_PREVENT_PICKUP, TEXT("InventorySample.Item.Behaviour.Transient.PreventPickup"));
// @gdemers InventorySample.Item.Slot
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_SLOT_ANY, TEXT("InventorySample.Item.Slot.Any"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_SLOT_ACTIVE, TEXT("InventorySample.Item.Slot.Active"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_SLOT_PASSIVE, TEXT("InventorySample.Item.Slot.Passive"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_SLOT_OFFENSIVE, TEXT("InventorySample.Item.Slot.Offensive"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_SLOT_DEFENSIVE, TEXT("InventorySample.Item.Slot.Defensive"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_SLOT_SUPPORT, TEXT("InventorySample.Item.Slot.Support"));
// @gdemers InventorySample.Item.Storage
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_STORAGE_PLAYER, TEXT("InventorySample.Item.Storage.Player"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_STORAGE_WORLD, TEXT("InventorySample.Item.Storage.World"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_STORAGE_FULL, TEXT("InventorySample.Item.Storage.State.Full"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_STORAGE_EMPTY, TEXT("InventorySample.Item.Storage.State.Empty"));
// @gdemers InventorySample.Item.Notification
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_NOTIFICATION_PICKUP, TEXT("InventorySample.UIChannel.HUDNotification.Pickup"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_NOTIFICATION_SWAP, TEXT("InventorySample.UIChannel.HUDNotification.Swap"));
UE_DEFINE_GAMEPLAY_TAG(TAG_INVENTORYSAMPLE_ITEM_NOTIFICATION_DROP, TEXT("InventorySample.UIChannel.HUDNotification.Drop"));
