//Copyright(c) 2025 gdemers
//
//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files(the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and /or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions :
//
//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//SOFTWARE.
#include "Tags/AVVMGameplayTags.h"

// @gdemers AVVMGameplay.GameState
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_GAMESTATE_ONPLAYERSTATE_ADDED_OR_REMOVED, "AVVMGameplay.GameState.OnPlayerState.AddedOrRemoved");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_GAMESTATE_MATCH_WAITING, "AVVMGameplay.GameState.Match.Waiting");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_GAMESTATE_MATCH_STARTED, "AVVMGameplay.GameState.Match.Started");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_GAMESTATE_MATCH_ENDED, "AVVMGameplay.GameState.Match.Ended");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_GAMESTATE_MATCH_LEAVINGMAP, "AVVMGameplay.GameState.Match.LeavingMap");
// @gdemers AVVMGameplay.MovementState
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_IDLE, "AVVMGameplay.Player.MovementState.Idle");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_WALK, "AVVMGameplay.Player.MovementState.Walk");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_SPRINT, "AVVMGameplay.Player.MovementState.Sprint");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_RUN, "AVVMGameplay.Player.MovementState.Run");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_SLIDING, "AVVMGameplay.Player.MovementState.Sliding");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_CHARGING, "AVVMGameplay.Player.MovementState.Charging");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_SWIMMING, "AVVMGameplay.Player.MovementState.Swimming");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_GLIDING, "AVVMGameplay.Player.MovementState.Gliding");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_MANTLING, "AVVMGameplay.Player.MovementState.Mantling");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_VAULTING, "AVVMGameplay.Player.MovementState.Vaulting");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_PRONE, "AVVMGameplay.Player.MovementState.Prone");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_CROUCHING, "AVVMGameplay.Player.MovementState.Crouching");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_STANDING, "AVVMGameplay.Player.MovementState.Standing");
// @gdemers AVVMGameplay.Status
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_STATUS_STATE_GROUND, "AVVMGameplay.Player.Status.Ground");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_STATUS_STATE_AIR, "AVVMGameplay.Player.Status.Air");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_STATUS_STATE_DOWN, "AVVMGameplay.Player.Status.Down");
UE_DEFINE_GAMEPLAY_TAG(TAG_AVVMGAMEPLAY_PLAYER_STATUS_STATE_RAGDOLL, "AVVMGameplay.Player.Status.RagDoll");
