//Copyright(c) 2025 gdemers
//
//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files(the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and /or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions :
//
//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//SOFTWARE.
#include "NativeGameplayTags.h"

// @gdemers AVVMGameplay.GameState
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_GAMESTATE_ONPLAYERSTATE_ADDED_OR_REMOVED);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_GAMESTATE_MATCH_WAITING);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_GAMESTATE_MATCH_STARTED);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_GAMESTATE_MATCH_ENDED);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_GAMESTATE_MATCH_LEAVINGMAP);
// @gdemers AVVMGameplay.MovementState
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_IDLE);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_WALK);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_SPRINT);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_RUN);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_SLIDING);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_CHARGING);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_SWIMMING);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_GLIDING);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_MANTLING);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_VAULTING);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_PRONE);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_CROUCHING);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_MOVEMENT_STATE_STANDING);
// @gdemers AVVMGameplay.Status
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_STATUS_STATE_GROUND);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_STATUS_STATE_AIR);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_STATUS_STATE_DOWN);
AVVMGAMEPLAY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AVVMGAMEPLAY_PLAYER_STATUS_STATE_RAGDOLL);
