[DeviceProfiles]
+DeviceProfileNameAndTypes=SixtyHertz_Windows_60,Windows

[SixtyHertz_Windows_60 DeviceProfile]
DeviceType=Windows
BaseProfileName=Windows
+CVars=sg.ViewDistanceQuality=2
+CVars=sg.AntiAliasingQuality=2
+CVars=sg.ShadowQuality=2
+CVars=sg.GlobalIlluminationQuality=2
+CVars=sg.ReflectionQuality=2
+CVars=sg.PostProcessQuality=2
+CVars=sg.TextureQuality=2
+CVars=sg.EffectsQuality=2
+CVars=sg.FoliageQuality=2
+CVars=sg.ShadingQuality=2
+CVars=sg.LandscapeQuality=2

; for static res platforms
+CVars=r.ScreenPercentage=75
+CVars=r.SecondaryScreenPercentage.GameViewport=65

; for dynamic res platforms
+CVars=r.DynamicRes.FrameTimeBudget=16.66
+CVars=r.DynamicRes.MinScreenPercentage=55
+CVars=r.DynamicRes.MaxScreenPercentage=75