//Copyright(c) 2025 gdemers
//
//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files(the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and /or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions :
//
//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//SOFTWARE.
#include "AVVMPredictiveInputIndexObject.h"

FAVVMPredictiveInputIndexObject::FAVVMPredictiveInputIndexObject(TFunction<bool(const int32)> OnNewPause,
                                                                 TFunction<bool(const int32)> OnNewRestore,
                                                                 TFunction<bool(const int32)> OnNewRestart,
                                                                 const int32 ReserveArraySize)
	: OnPause(MoveTemp(OnNewPause)),
	  OnRestore(MoveTemp(OnNewRestore)),
	  OnRestart(MoveTemp(OnNewRestart))

{
	PredictiveInputIndexes.SetNumZeroed(ReserveArraySize);
}

bool UAVVMPredictiveInputUtils::Capture(const int32 NewInputIndex,
                                        FAVVMPredictiveInputIndexObject& OutResult)
{
	if (!ensureAlwaysMsgf(OutResult.OnPause.IsSet(), TEXT("Delegate missing binding.")) ||
		!ensureAlwaysMsgf(OutResult.OnRestore.IsSet(), TEXT("Delegate missing binding.")) ||
		!ensureAlwaysMsgf(OutResult.OnRestart.IsSet(), TEXT("Delegate missing binding.")))
	{
		return false;
	}

	const int32 PrevCapturedInputIndex = (OutResult.PrevInputIndex != INDEX_NONE) ? OutResult.PrevInputIndex : NewInputIndex;
	const int32 NextCapturedInputIndex = NewInputIndex;

	// @gdemers Pause any animation that may be running on the currently active instance, or set pending kill already paused animation.
	if (ensureAlwaysMsgf(OutResult.PredictiveInputIndexes.IsValidIndex(PrevCapturedInputIndex),
	                     TEXT("Invalid KVP.")))
	{
		auto& OutPrevEnumResult = OutResult.PredictiveInputIndexes[PrevCapturedInputIndex];

		const bool bShouldPause = (OutPrevEnumResult == EPredictiveState::Running);
		if (bShouldPause)
		{
			OutPrevEnumResult = EPredictiveState::Paused;
			OutResult.OnPause(PrevCapturedInputIndex);
		}
		else if ((PrevCapturedInputIndex != NextCapturedInputIndex) && (OutPrevEnumResult == EPredictiveState::Paused))
		{
			OutPrevEnumResult = EPredictiveState::PendingKill;
		}
	}

	// @gdemers Restore/Restart any animation that may have been paused due to desync, old state invalidation, or based on rapid sequence of user updates.
	if (!ensureAlwaysMsgf(OutResult.PredictiveInputIndexes.IsValidIndex(NextCapturedInputIndex),
	                      TEXT("Invalid KVP.")))
	{
		return false;
	}

	auto& OutCurrEnumResult = OutResult.PredictiveInputIndexes[NextCapturedInputIndex];

	const bool bShouldRestore = (OutCurrEnumResult == EPredictiveState::Paused);
	if (bShouldRestore)
	{
		OutCurrEnumResult = EPredictiveState::Running;
		OutResult.OnRestore(NextCapturedInputIndex);
	}
	else if (OutCurrEnumResult != EPredictiveState::Running)
	{
		// @gdemers we want to prevent duplicated call to restart generated by latent synchronization on client.
		OutCurrEnumResult = EPredictiveState::Running;
		OutResult.OnRestart(NextCapturedInputIndex);
	}

	OutResult.PrevInputIndex = NextCapturedInputIndex;
	return true;
}

bool UAVVMPredictiveInputUtils::Flush(FAVVMPredictiveInputIndexObject& OutResult)
{
	// TODO @gdemers add impl
	return true;
}
